(inline "(" @left.round (#set! "right" ")"))
(inline ")" @right.round)
(inline "[" @left.square (#set! "right" "]"))
(inline "]" @right.square)

(inline_link "(" @left.round (#set! "right" ")"))
(inline_link ")" @right.round)
(inline_link "[" @left.square (#set! "right" "]"))
(inline_link "]" @right.square)
(shortcut_link "[" @left.square (#set! "right" "]"))
(shortcut_link "]" @right.square)
